### ISSUE TITLE
Discussion about the future work

### ISSUE THREAD

**Issue by STAY-Melody** [qgallouedec/panda-gym#82]
Hi!

Thanks for your excellent work which has benefited me a lot.

In your paper, the other modalities with RGB, depth, force sensor, and tactile sensor input of `panda-gym` were listed as future work.

For now, `panda-gym` has evolved into v3. If the other modalities are still considered to be updated?

Thanks!

**Comment by qgallouedec** [comment]
Hi, thanks for your question.

I considered these evolutions following the paper. My conclusion is that PyBullet does not allow you to do everything related to images in a reasonable time. When you want to render every step, it takes a long time, even with the tiny renderer (you drop from 760 FPS to 4!).

```python
import time

import gymnasium as gym
from gymnasium.wrappers import PixelObservationWrapper

import panda_gym

env = gym.make("PandaPickAndPlace-v3", renderer="Tiny")
env = PixelObservationWrapper(env, pixels_only=True)
env.reset()
start = time.time()
for i in range(100):
    env.step(env.action_space.sample())
stop = time.time()
print("FPS: {:.2f}".format(100 / (stop - start)))
```

To do this with reasonable speed, you'd have to migrate to more powerful rendering engines, like MuJoCo, and that's not planned.


As for the force sensor, I haven't implemented it, mainly because I think it's a matter for specific studies, and users are free to fork and adapt it according to their needs.
For the records, pybullet does allow this. Here's a hacky example to print the force at a finger joint:

```python
import gymnasium as gym


class PrintForceWrapper(gym.Wrapper):
    def __init__(self, env):
        super().__init__(env)
        self.body_id = self.env.sim._bodies_idx[self.env.robot.body_name]
        self.joint_idx = self.env.robot.joint_indices[0]
        self.env.sim.physics_client.enableJointForceTorqueSensor(self.body_id, self.joint_idx)

    def step(self, action):
        r = super().step(action)
        joint_state = self.env.sim.physics_client.getJointState(self.body_id, self.joint_idx)
        force = joint_state[2][:3]
        print("Force: ", force)
        return r


env = gym.make("PandaPickAndPlace-v3")
env = PrintForceWrapper(env)

env.reset()
for _ in range(100):
    env.step(env.action_space.sample())
```

I'm still open to contributions, though. If the majority thinks it's an interesting feature to add, then we can add it.

**Comment by qgallouedec** [comment]
Not to my knowledge. If you find any references, please share them here.
You can do basic training with multimodal observation (image and desired goal, as x, y, z target position) using sb3 like this:

```python
import gymnasium as gym
from gymnasium.wrappers import FilterObservation, PixelObservationWrapper
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv

import panda_gym


class ObsToImageWrapper(gym.Wrapper):
    def __init__(self, env):
        env = PixelObservationWrapper(env, pixels_only=False)
        env = FilterObservation(env, ["pixels", "desired_goal"])
        super().__init__(env)


def main():
    env = make_vec_env(
        "PandaReach-v3",
        n_envs=16,
        wrapper_class=ObsToImageWrapper,
        vec_env_cls=SubprocVecEnv,
        env_kwargs={"renderer": "Tiny", "render_width": 84, "render_height": 84},
    )

    model = PPO("MultiInputPolicy", env, verbose=1)
    model.learn(total_timesteps=1000000)


if __name__ == "__main__":
    main()
```

Note that you must use the tiny renderer because pybullet doesn't support multithreading with OpenGL.

As I suspected, the training is quite slow, due to the simulation (around 100 FPS with 16 workers, far from the best case mentioned above).

**Comment by qgallouedec** [comment]
> For the image input, the desired goal can also be represented as the vector of x, y, and z coordinates of the target.

I'm not sure to understand. In the provided code, the input of the agent is actually composed of (1) the image and (2) the desired obs as (x, y, z).

> So, is the rest of the information, such as the position and velocity of the end-effector, still necessary?

Again, it depends on what you want to do. In the provided code, these values aren't part of the input. 
In a scenario closer to reality, you could also include in the observation the data related to the robot, but not the data related to the object. And let the agent infer the object's position from the image.

> If necessary, should the rendered image be compressed in advance via CNN to reduce dimensionality? Thanks.

It depends on what you want to prove. For example, this work is focused on decoupling feature learning from policy learning. https://openreview.net/forum?id=Hkl-di09FQ
